name: enderpay
version: '1.4.1-SNAPSHOT'
main: com.withorcc.enderpay.Enderpay
api-version: '1.20'
load: STARTUP
commands:
  bank:
    description: Your description
    usage: /<command>
    permission: bank.cmd